# Generated by Django 2.2.7 on 2019-11-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='secret',
            field=models.BooleanField(default=False),
        ),
    ]
