# Generated by Django 2.2.7 on 2019-11-25 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_en', models.CharField(max_length=100)),
                ('audience', models.IntegerField()),
                ('poster_url', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('running_time', models.CharField(max_length=30)),
                ('directors', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
                ('watch_grade', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('review_link', models.CharField(max_length=200)),
                ('preview_link', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=100)),
                ('liked_users', models.ManyToManyField(related_name='liked_movies', to=settings.AUTH_USER_MODEL)),
                ('recommend_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140)),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.Movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
