# Generated by Django 2.2.7 on 2019-11-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_open_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
