# Generated by Django 2.2.7 on 2019-11-27 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_recommendation_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='level',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='movie',
            name='liked_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
