# Generated by Django 2.2.7 on 2019-11-27 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20191127_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
